server:
  applicationConnectors:
    - type: http
      port: 9000
      maxRequestHeaderSize: ${MAX_REQ_HEADER_SIZE:-16KiB}
      maxResponseHeaderSize: ${MAX_RESP_HEADER_SIZE:-16KiB}
  adminConnectors:
    - type: http
      port: 9001

logging:
  loggers:
    io.cratekube: DEBUG
    org.reflections: ERROR

swagger:
  resourcePackage: io.cratekube.clustermgmt.resources

rke:
  nodeUser: ${RKE_NODE_USER:-ubuntu}
  sshKeyPath: ${RKE_PRIVATE_KEY_PATH:-~/.ssh/id_rsa}
  podSecurityPolicyEnabled: ${RKE_POD_SECURITY_POLICY_ENABLED:-false}

configLocation: ${CONFIG_LOCATION:-/app/config}

auth:
  apiKeys:
    - name: admin
      key: ${ADMIN_APIKEY:-}
      roles: ['admin']

jerseyClient:
  timeout: ${JERSEY_CLIENT_TIMEOUT:-5000ms}
  connectionTimeout: ${JERESEY_CLIENT_CONNECT_TIMEOUT:-5000ms}
  connectionRequestTimeout: ${JERESEY_CLIENT_CONNECT_REQUEST_TIMEOUT:-5000ms}
  gzipEnabledForRequests: false
